name: Test Podman Security Connectivity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-security-connectivity:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit
          allowed-endpoints: >
            8.8.8.8:53
            8.8.4.4:53
            1.1.1.1:53
            1.0.0.1:53
            
      - name: Install Podman
        run: |
          echo "Installing Podman..."
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version
          
      - name: Setup Podman BuildKit
        run: |
          echo "Setting up Podman BuildKit..."
          chmod +x ./scripts/setup-podman.sh
          ./scripts/setup-podman.sh &
          SETUP_PID=$!
          
          # Wait for setup to complete and capture environment
          wait $SETUP_PID
          SETUP_EXIT_CODE=$?
          
          if [ $SETUP_EXIT_CODE -ne 0 ]; then
            echo "Setup script failed with exit code $SETUP_EXIT_CODE"
            exit 1
          fi
          
          echo "Podman BuildKit setup completed"
          
      - name: Test DNS Resolution for Security Debian Repository
        run: |
          echo "Testing DNS resolution for security.debian.org..."
          
          # Test DNS resolution using busybox (has nslookup pre-installed)
          if podman run --rm --dns=8.8.8.8 --dns=8.8.4.4 --dns=1.1.1.1 --dns=1.0.0.1 \
            docker.io/busybox:latest \
            nslookup security.debian.org 2>&1; then
            echo "DNS resolution test: SUCCESS"
          else
            echo "DNS resolution test: FAILED"
            exit 1
          fi
          
          echo "DNS test completed successfully!"